styles:
  templates:
    layoutRootPath: EXT:aws_start_screen/Resources/Private/Layouts/
    partialRootPath: EXT:aws_start_screen/Resources/Private/Partials/
    templateRootPath: EXT:aws_start_screen/Resources/Private/Templates/
